config/routes.rb
Rails.application.routes.draw do

  scope module: 'user' do
    devise_for :users, controllers: {
      sessions: 'user/users/sessions',
      registrations: 'user/users/registrations',
      passwords: 'user/users/passwords'
    }
  end

  scope module: 'user' do
  	root :to => 'tops#top'
    get 'user_list' => 'users#user_list'
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :following, :followers
        get :matching
      end
    end
    resources :rooms, only: [:index, :show, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :posts do
   	  resources :post_goods, only: [:create, :destroy]
   	  resources :post_comments, only: [:create, :destroy]
    end
  end


end

app/models/user.rb
class User < ApplicationRecord

  attachment :image
  # ユーザー名1~15文字以内
  validates :user_name, length: { in: 1..15 }
  # 新規登録時性別記入必須にするため
  validates :sex, presence:true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum sex: {男性: 0, 女性: 1}

         enum area: {
            "---":0,
			北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
			茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
		    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
			岐阜県:21,静岡県:22,愛知県:23,三重県:24,
			滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
			鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
			徳島県:36,香川県:37,愛媛県:38,高知県:39,
			福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
			沖縄県:47
			}

	has_many :posts, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :post_goods, dependent: :destroy
	has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
	has_many :followings, through: :following_relationships
	has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
    has_many :followers, through: :follower_relationships
    has_many :entries
    has_many :chat_messages
    has_many :rooms, through: :entries
    has_many :user_hobby_maps, dependent: :destroy
    has_many :hobbies, through: :user_hobby_maps

	def following?(other_user)
		following_relationships.find_by(following_id: other_user.id)
	end

	def follow!(other_user)
		following_relationships.create!(following_id: other_user.id)
	end

	def unfollow!(other_user)
		following_relationships.find_by(following_id: other_user.id).destroy
	end

	def save_hobby(sent_hobbies)
	    current_hobbies = self.hobbies.pluck(:hobby_name) unless self.hobbies.nil?
	    old_hobbies = current_hobbies - sent_hobbies
	    new_hobbies = sent_hobbies - current_hobbies

	    old_hobbies.each do |old|
	      self.hobbies.delete Hobby.find_by(hobby_name: old)
	    end

	    new_hobbies.each do |new|
	      new_hobby = Hobby.find_or_create_by(hobby_name: new)
	      self.hobbies << new_hobby
	    end
    end
end

app/controllers/user/chat_messages_controller.rb
class User::ChatMessagesController < ApplicationController
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController

	def create
		post =Post.find(params[:post_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.post_id = post.id
		comment.save
		redirect_to post_path(post)
	end

	def destroy
		PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
		redirect_to post_path(params[:post_id])
    end

    private
    def post_comment_params
    	params.require(:post_comment).permit(:comment)
    end
end

app/controllers/user/post_goods_controller.rb
class User::PostGoodsController < ApplicationController
	def create
		post = Post.find(params[:post_id])
		post_good = current_user.post_goods.new(post_id: post.id)
		post_good.save
		redirect_to post_path(post)
	end

	def destroy
		post = Post.find(params[:post_id])
		post_good = current_user.post_goods.find_by(post_id: post.id)
		post_good.destroy
		redirect_to post_path(post)
	end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :user_check, only: [:edit, :update]

  def index
  	@posts = Post.all
    @hobby_list = Hobby.all
  end

  def new
  	@post = current_user.posts.new
  end

  def create
  	@post = current_user.posts.new(post_params)
    hobby_list = params[:post][:hobby_name].split(nil)
    @post.save
    @post.save_hobby(hobby_list)
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @post_hobbies = @post.hobbies
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    hobby_list = params[:post][:hobby_name].split(nil)
    @post.user_id = current_user.id
    @post.update(post_params)
    @post.save_hobby(hobby_list)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
  	params.require(:post).permit(:image, :body)
  end

  def user_check
     @post = Post.find(params[:id])

        if @post.user_id != current_user.id
          redirect_to post_path(@post.id)
        end
  end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
	def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController


	def index
		@user = current_user
		@current_entries = current_user.entries
		my_room_ids = []
		@current_entries.each do |entry|
			my_room_ids << entry.room.id
		end
		@another_entries = Entry.where(room_id: my_room_ids).where.not(user_id: @user.id).order(created_at: :desc)
	end

	def show
		@room = Room.find(params[:id])
		if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
			@chat_messages = @room.chat_messages
			@entries = @room.entries
		else
		    redirect_back(fallback_location: users_path)
		end
	end

	def create
		@room = Room.create(:name => "chat")
		@entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
		@entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
		redirect_to room_path(@room.id)
	end

	def destroy
		room = Room.find(params[:id])
		room.destroy
		redirect_to rooms_path
	end

end

app/controllers/user/tops_controller.rb
class User::TopsController < ApplicationController
	skip_before_action :authenticate_user!
	def top
	end
end

app/controllers/user/users/confirmations_controller.rb
# frozen_string_literal: true

class User::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/users/passwords_controller.rb
# frozen_string_literal: true

class User::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/users/registrations_controller.rb
# frozen_string_literal: true

class User::Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     edit_user_path(resource)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users/sessions_controller.rb
# frozen_string_literal: true

class User::Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/users/unlocks_controller.rb
# frozen_string_literal: true

class User::Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :user_check, only: [:matching, :following, :followers, :update, :edit]

  def index
  end

  def user_list
    @users = User.all
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def matching
    @users = current_user.followings & current_user.followers
  end

  def show
    @user = User.find(params[:id])
    @user_hobbies = @user.hobbies
    @user_posts = @user.posts
    #byebug
    #@is_match = current_user.following?(@user) && @user.following?(current_user)
    #チャット機能
    if user_signed_in?
      @current_user_entry = Entry.where(user_id: current_user.id)
      @user_entry = Entry.where(user_id: @user.id)
        unless @user.id == current_user.id
          @current_user_entry.each do |cu|
            @user_entry.each do |u|
              if cu.room_id == u.room_id then
                @is_room = true
                @room_id = cu.room_id
              end
            end
          end
          unless @is_room
            @room = Room.new
            @entry = Entry.new
          end
        end
    end
  end

  def edit
  	@user = User.find(params[:id])
    @hobby_list = @user.hobbies.pluck(:hobby_name).join(nil)
  end

  def update
  	@user = User.find(params[:id])
    hobby_list = params[:user][:hobby_name].split(nil)
    @user.update_attributes(user_params)
    @user.save_hobby(hobby_list)
    redirect_to user_path(@user.id)
  end


  private
  def user_params
    params.require(:user).permit(:user_name, :image, :sex, :area, :introduction)
  end

  def user_check
    @user = User.find(params[:id])

        if @user.id != current_user.id
          redirect_to users_path
        end
  end
end

app/helpers/user/chat_messages_helper.rb
module User::ChatMessagesHelper
end

app/helpers/user/post_comments_helper.rb
module User::PostCommentsHelper
end

app/helpers/user/post_goods_helper.rb
module User::PostGoodsHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/relationships_helper.rb
module User::RelationshipsHelper
end

app/views/user/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/user/users/_follow_form.html.erb
<!--他ユーザーフォロー機能-->
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/user/users/_list.html.erb
<table class="table table-hover">
	<thead>
	</thead>
	<tbody>
		<tr>
		  <td>
		  <%= link_to user_path(user), class:"text-secondary" do %>
	  	  <%= attachment_image_tag user, :image, :fill, 100, 100, fallback: 'no_image.jpg' %>
	      <%= user.user_name %>
	      <% end %>
		  <!-- 年齢 -->
		  <% now_age = (Date.today.strftime('%Y%m%d').to_i - user.age.strftime('%Y%m%d').to_i) / 10000 %>
		  <%= now_age %>
		  <!-- 性別 -->
		  <%= user.sex %>
		  </td>
		  <!-- 居住地 -->
		  <td><%= user.area %></td>
		  <!-- 趣味 -->
		  <td>
	      </td>
		</tr>
	</tbody>
</table>

app/views/user/users/_sidemenu.html.erb
<nav class="pl-5 navbar navbar-fixed-left">
	<ul class="list-unstyled">
		<li><p class="pt-4"><%= attachment_image_tag current_user, :image, :fill, 100, 100, fallback: 'no_image.jpg' %>
		<%= current_user.user_name %></p></li>
	    <li><h4 class="pt-4">
		  <%= link_to "プロフィール", user_path(current_user.id), class:"text-secondary" %>
		</h4></li>
		<li><h4 class="pt-4">
			  <%= link_to 'チャット', rooms_path(current_user), class:"text-secondary" %>
		</h4></li>
		<li><h4 class="pt-4">
		  <%= link_to '投稿する', new_post_path, class:"text-secondary" %>
		</h4></li>
    </ul>
</nav>

app/views/user/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー外す", class: "btn btn-large follow-btn" %>
<% end %>

app/views/user/users/edit.html.erb
<!-- ユーザー情報編集画面 -->
<div class="container">
	<div class="row d-flex align-items-center justify-content-center pt-2">
		<div class="text-center">
			<h1>プロフィール編集</h1>
			<%= form_with model: @user, local: true do |f| %>
		   <div class="pt-4">
		   	 <!-- 画像ファイルアップロード -->
			 <%= f.attachment_field :image, class: 'img_field', style: 'display:none' %>
			 <!-- 画像プレビュー機能　image_preview.jsから読み込み -->
			 <%= attachment_image_tag @user, :image, :fill, 300, 300, fallback: 'no_image.jpg', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev', :width => "300", :height => "300" %>
		   </div>
			<div class="pt-4">
			 <table>
			 	<div class="form-group">
				 	<tr>
				 		<th><h4>ユーザー名 : </h4></th>
				 		<td><%= f.text_field :user_name, class:"form-control" %></td>
				 	</tr>
				 	<tr>
				 		<th><h4>居住地 : </h4></th>
				 		<td>　<%= f.select :area, User.areas.keys, {}, class:"form-control" %>
				 		</td>
				 	</tr>
				 	<tr>
				 		<th><h4>趣味</h4></th>
				 		<td> <%= f.text_field :hobby_name, value: @hobby_lit, class:"form-control", placeholder:"※複数タグ付けする場合は趣味と趣味の間にスペースを入れてください"  %></td>
				 	</tr>
				 	<tr>
				 		<th><h4>自己紹介 : </h4></th>
				 		<td></td>
				 	</tr>
				 	<tr>
				 	  <div class="form-group">
				 		<th></th>
				 		<td><%= f.text_area :introduction, class:"form-control" %></td>
				 	  </div>
				 	</tr>
				 </table>
			</div>
			 <%= f.submit "変更する" %>
			<% end %>
		  </div>
		</div>
	</div>
</div>

app/views/user/users/index.html.erb
<div class="container">

	<div class="row d-flex align-items-center justify-content-center pt-5">
	  	<div class="text-center">
	  		<h2 Class="border border-dark rounded">マイページ</h2>
			<table>
				<tr>
					<td class="pt-4"><%= attachment_image_tag current_user, :image, :fill, 100, 100, fallback: 'no_image.jpg' %>
					<%= current_user.user_name %></td>
				</tr>
				<tr>
				  <td  class="pt-4">
						<!--フォロー、フォロワーの人数表示-->
				  <h4><%= link_to following_user_path(current_user.id), class:"text-secondary" do %>
				   <%= current_user.followings.count %>フォロー
				  <% end %>
				  <%= link_to followers_user_path(current_user.id), class:"pl-3 text-secondary" do %>
				   <%= current_user.followers.count %>フォロワー
				  <% end %></h4>
						</td>
				</tr>
				<!-- マッチした人数のカウント -->
				<tr>
					<td class="pt-4">
						<h4>
						<%= link_to  matching_user_path(current_user.id), class:"text-secondary" do %>
						   <%= (current_user.followings & current_user.followers).count %>マッチ
						<% end %>
					    </h4>
					</td>
				</tr>
				<tr>
					<td class="pt-4">
				    <h4>
					  <%= link_to "プロフィール", user_path(current_user.id), class:"text-secondary" %>
					</h4>
					</td>
				</tr>
				<tr>
					<td class="pt-4">
						<h4>
						  <%= link_to 'チャット', rooms_path(current_user), class:"text-secondary" %>
						</h4>
					</td>
				</tr>
				<tr>
					<td class="pt-4">
						<h4>
						  <%= link_to '投稿する', new_post_path, class:"text-secondary" %>
						</h4>
					</td>
				</tr>
			</table>
		  </div>
    </div>
</div>

app/views/user/users/matching.html.erb
<dev class="container-fluid">
	<div class="row">
		<div class="col-3 text-center">
			<%= render 'sidemenu' %>
		</div>
		<div class="col-9">
			<h1>マッチした人一覧</h1>
			<div style="overflow:auto; height: 500px;">
				<% @users.each do |macth| %>
				<%= render 'list', user: macth %>
				<% end %>
			<div style="overflow:auto; height: 500px;">
        </div>
	</div>
</dev>

app/views/user/users/show.html.erb
<div class="container">
	<div class="row">
	  <div class="col-5">
	  	  <h2 class="text-center">プロフィール</h2>
	  	<div class="sidebar_fixed">
	  	 <div class="mx-auto">
		 <table>
		  <tr>
			<td><%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: 'no_image.jpg' %>
			    <%= @user.user_name %>
			</td>
		  </tr>
		  <tr>
		  	 <!-- 現在の年齢を算出 -->
			　<% now_age = (Date.today.strftime('%Y%m%d').to_i - @user.age.strftime('%Y%m%d').to_i) / 10000 %>
			<th>年齢 :</th><td><%= now_age %></td>
		  </tr>
		  <tr>
		  	<th>性別:</th>
			<td><%= @user.sex %></td>
		  </tr>
		  <tr>
		  	<th>住んでいる地域 : </th><td><%= @user.area %></td>
		  </tr>
		  <!--趣味のタグ付け-->
		  <tr>
		  	<th><h4>趣味</h4></th>
		  	<td>
			　<% @user_hobbies.each do |hobby| %>
		        <span><%= hobby.hobby_name %></span>
		      <% end %>
		    </td>
		  </tr>
		  <tr>
		  	<td>
			<h4>自己紹介</h4>
			<%= @user.introduction %>
			</td>
		  </tr>
		  <tr>
		  	<td>
             <!-- フォロー機能rendar -->
			<%= render 'follow_form' %>
		    </td>
		  </tr>
		  <tr>
		  	<td>
				<!--chat機能（DM）-->
				<% if user_signed_in? %>
					<% unless @user.id == current_user.id %>
					  <% if current_user.following?(@user) && @user.following?(current_user) %>
						<% if @is_room == true %>
							<%= link_to room_path(@room_id) do %>
							   <button class="btn btn-outline-primary" id="dm_submit">チャット</button>
							<% end %>
						 <% else %>
							<%= form_for @room, url: rooms_path do |f| %>
								<%= fields_for @entry do |e| %>
									<%= e.hidden_field :user_id, :value => @user.id %>
								<% end %>
									<button class="btn btn-outline-primary" type="submit" id="chat_submit">チャット</button>
							<% end %>
						<% end %>
						<% end %>
					<% end %>
				<% end %>
		    </td>
		  </tr>
		</table>
			<!--自分のプロフィールの場合のみ表示する-->
				<% if @user.id == current_user.id %>
				  <p><%= link_to "編集する", edit_user_path(current_user.id), class:"btn btn-outline-success" %></p>
				  <p><%= link_to "マイページへ", users_path, class:"btn btn-outline-primary" %></p>
				<% end %>
			<!-- ここまで -->
		 </div>
		</div>
	  </div>
	  <!-- 詳細を表示しているユーザーの投稿一覧 -->
	  <div class="col-7">
	  	   <div style="overflow:auto; height: 500px;">
					<% @user_posts.each do |cp| %>
					     <%= render 'user/posts/timeline', post: cp %>
					<% end %>
			</div>
        </div>
	</div>
</div>

app/views/user/users/show_follow.html.erb
<dev class="container-fluid">
	<div class="row">
		<div class="col-3 text-center">
			<%= render 'sidemenu' %>
		</div>
		<div class="col-9">
			<h1>フォローリスト</h1>
			<div style="overflow:auto; height: 500px;">
			 <% @user.followings.each do |user| %>
			 <%= render 'list', user: user %>
			 <% end %>
		    </div>
		</div>
	</div>
</dev>

app/views/user/users/show_follower.html.erb
<!-- フォロワー一覧 -->
<dev class="container-fluid">
	<div class="row">
		<div class="col-3 text-center">
			<%= render 'sidemenu' %>
		</div>
		<div class="col-9">
			<h1>フォロワーリスト</h1>
			<div style="overflow:auto; height: 500px;">
			  <% @user.followers.each do |user| %>
			  <%= render 'list', user: user %>
			  <% end %>
		    </div>
		</div>
	</div>
</dev>

app/views/user/users/user_list.html.erb
<!-- 自分以外のユーザー一覧 -->
<dev class="container-fluid">
	<div class="row">
		<div class="col-3 text-center">
			<%= render 'sidemenu' %>
		</div>
		<div class="col-9">
		  <h2>趣味仲間を探す</h2>
		   <div style="overflow:auto; height: 500px;">
				<% @users.each do |user| %>
					 <!-- ログインユーザーは表示させない -->
					 <% if user.id != current_user.id %>
				        <%= render 'list', user: user %>
				     <% end %>
			    <% end %>
			</div>
		</div>
	</div>
</dev>