config/routes.rb
Rails.application.routes.draw do

  scope module: 'user' do
    devise_for :users, controllers: {
      sessions: 'user/users/sessions',
      registrations: 'user/users/registrations',
      passwords: 'user/users/passwords'
    }
  end

  scope module: 'user' do
  	root :to => 'tops#top'
    get 'user_list' => 'users#user_list'
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :following, :followers
        get :matching
      end
    end
    resources :rooms, only: [:index, :show, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :posts do
   	  resources :post_goods, only: [:create, :destroy]
   	  resources :post_comments, only: [:create, :destroy]
    end
  end


end

app/models/post.rb
class Post < ApplicationRecord

	default_scope -> { order(created_at: :desc) }
	attachment :image

    belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :post_goods, dependent: :destroy
	has_many :hobby_maps, dependent: :destroy
	has_many :hobbies, through: :hobby_maps

   def post_gooded_by?(user)
    post_goods.where(user_id: user.id).exists?
   end

   def save_hobby(sent_hobbies)
    current_hobbies = self.hobbies.pluck(:hobby_name) unless self.hobbies.nil?
    old_hobbies = current_hobbies - sent_hobbies
    new_hobbies = sent_hobbies - current_hobbies

    old_hobbies.each do |old|
      self.hobbies.delete Hobby.find_by(hobby_name: old)
    end

    new_hobbies.each do |new|
      new_hobby = Hobby.find_or_create_by(hobby_name: new)
      self.hobbies << new_hobby
    end
   end


end

app/models/user.rb
class User < ApplicationRecord

  attachment :image
  # ユーザー名1~15文字以内
  validates :user_name, length: { in: 1..15 }
  # 新規登録時性別記入必須にするため
  validates :sex, presence:true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum sex: {男性: 0, 女性: 1}

         enum area: {
            "---":0,
			北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
			茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
		    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
			岐阜県:21,静岡県:22,愛知県:23,三重県:24,
			滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
			鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
			徳島県:36,香川県:37,愛媛県:38,高知県:39,
			福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
			沖縄県:47
			}

	has_many :posts, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :post_goods, dependent: :destroy
	has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
	has_many :followings, through: :following_relationships
	has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
    has_many :followers, through: :follower_relationships
    has_many :entries
    has_many :chat_messages
    has_many :rooms, through: :entries
    has_many :user_hobby_maps, dependent: :destroy
    has_many :hobbies, through: :user_hobby_maps

	def following?(other_user)
		following_relationships.find_by(following_id: other_user.id)
	end

	def follow!(other_user)
		following_relationships.create!(following_id: other_user.id)
	end

	def unfollow!(other_user)
		following_relationships.find_by(following_id: other_user.id).destroy
	end

	def save_hobby(sent_hobbies)
	    current_hobbies = self.hobbies.pluck(:hobby_name) unless self.hobbies.nil?
	    old_hobbies = current_hobbies - sent_hobbies
	    new_hobbies = sent_hobbies - current_hobbies

	    old_hobbies.each do |old|
	      self.hobbies.delete Hobby.find_by(hobby_name: old)
	    end

	    new_hobbies.each do |new|
	      new_hobby = Hobby.find_or_create_by(hobby_name: new)
	      self.hobbies << new_hobby
	    end
    end
end

app/controllers/user/chat_messages_controller.rb
class User::ChatMessagesController < ApplicationController
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController

	def create
		post =Post.find(params[:post_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.post_id = post.id
		comment.save
		redirect_to post_path(post)
	end

	def destroy
		PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
		redirect_to post_path(params[:post_id])
    end

    private
    def post_comment_params
    	params.require(:post_comment).permit(:comment)
    end
end

app/controllers/user/post_goods_controller.rb
class User::PostGoodsController < ApplicationController
	def create
		post = Post.find(params[:post_id])
		post_good = current_user.post_goods.new(post_id: post.id)
		post_good.save
		redirect_to post_path(post)
	end

	def destroy
		post = Post.find(params[:post_id])
		post_good = current_user.post_goods.find_by(post_id: post.id)
		post_good.destroy
		redirect_to post_path(post)
	end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :user_check, only: [:edit, :update]

  def index
  	@posts = Post.all
    @hobby_list = Hobby.all
  end

  def new
  	@post = current_user.posts.new
  end

  def create
  	@post = current_user.posts.new(post_params)
    hobby_list = params[:post][:hobby_name].split(nil)
    @post.save
    @post.save_hobby(hobby_list)
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @post_hobbies = @post.hobbies
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    hobby_list = params[:post][:hobby_name].split(nil)
    @post.user_id = current_user.id
    @post.update(post_params)
    @post.save_hobby(hobby_list)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
  	params.require(:post).permit(:image, :body)
  end

  def user_check
     @post = Post.find(params[:id])

        if @post.user_id != current_user.id
          redirect_to post_path(@post.id)
        end
  end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
	def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController


	def index
		@user = current_user
		@current_entries = current_user.entries
		my_room_ids = []
		@current_entries.each do |entry|
			my_room_ids << entry.room.id
		end
		@another_entries = Entry.where(room_id: my_room_ids).where.not(user_id: @user.id).order(created_at: :desc)
	end

	def show
		@room = Room.find(params[:id])
		if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
			@chat_messages = @room.chat_messages
			@entries = @room.entries
		else
		    redirect_back(fallback_location: users_path)
		end
	end

	def create
		@room = Room.create(:name => "chat")
		@entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
		@entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
		redirect_to room_path(@room.id)
	end

	def destroy
		room = Room.find(params[:id])
		room.destroy
		redirect_to rooms_path
	end

end

app/controllers/user/tops_controller.rb
class User::TopsController < ApplicationController
	skip_before_action :authenticate_user!
	def top
	end
end

app/controllers/user/users/confirmations_controller.rb
# frozen_string_literal: true

class User::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/users/passwords_controller.rb
# frozen_string_literal: true

class User::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/users/registrations_controller.rb
# frozen_string_literal: true

class User::Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     edit_user_path(resource)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users/sessions_controller.rb
# frozen_string_literal: true

class User::Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/users/unlocks_controller.rb
# frozen_string_literal: true

class User::Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :user_check, only: [:matching, :following, :followers, :update, :edit]

  def index
  end

  def user_list
    @users = User.all
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def matching
    @users = current_user.followings & current_user.followers
  end

  def show
    @user = User.find(params[:id])
    @user_hobbies = @user.hobbies
    @user_posts = @user.posts
    #byebug
    #@is_match = current_user.following?(@user) && @user.following?(current_user)
    #チャット機能
    if user_signed_in?
      @current_user_entry = Entry.where(user_id: current_user.id)
      @user_entry = Entry.where(user_id: @user.id)
        unless @user.id == current_user.id
          @current_user_entry.each do |cu|
            @user_entry.each do |u|
              if cu.room_id == u.room_id then
                @is_room = true
                @room_id = cu.room_id
              end
            end
          end
          unless @is_room
            @room = Room.new
            @entry = Entry.new
          end
        end
    end
  end

  def edit
  	@user = User.find(params[:id])
    @hobby_list = @user.hobbies.pluck(:hobby_name).join(nil)
  end

  def update
  	@user = User.find(params[:id])
    hobby_list = params[:user][:hobby_name].split(nil)
    @user.update_attributes(user_params)
    @user.save_hobby(hobby_list)
    redirect_to user_path(@user.id)
  end


  private
  def user_params
    params.require(:user).permit(:user_name, :image, :sex, :area, :introduction)
  end

  def user_check
    @user = User.find(params[:id])

        if @user.id != current_user.id
          redirect_to users_path
        end
  end
end

app/helpers/user/chat_messages_helper.rb
module User::ChatMessagesHelper
end

app/helpers/user/post_comments_helper.rb
module User::PostCommentsHelper
end

app/helpers/user/post_goods_helper.rb
module User::PostGoodsHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/user/posts/_post_form.html.erb
<h1 class="text-center">投稿フォーム</h1>
		<%= form_with(model: @post, url: post_path(@post), local: true) do |f| %>

		  <div class="text-center">
		  	 <div class="form-group">
		  	 	<div class="pt-5">
		  	 	   <%= f.attachment_field :image, class: 'img_field', style: 'display:none' %>
			       <%= attachment_image_tag @post, :image, :fill, 300, 300, fallback: 'm_e_others_500.png', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev' %>
			    </div>
			    <div class="pt-4">
				   <h4>趣味</h4>
				   <%= f.text_field :hobby_name, class:"form-control", placeholder:"※複数タグ付けする場合は趣味と趣味の間にスペースを入れてください"  %>
				</div>
				<div class="pt-4">
				   <h4>内容</h4>
				   <%= f.text_area :body, class:"form-control pb-5" %>
				</div>
			  </div>
			     <% if 'posts#new' %>
			      <%= f.submit "投稿", class:"btn btn-outline-success btn-lg mt-5" %>
			     <% else %>
			      <%= f.submit "編集する" %>
			     <% end %>
		  </div>
		<% end %>

app/views/user/posts/_timeline.html.erb
<table>
	<tbody>
		     <tr>
		     	<td>
		     	<!-- レイアウトにbootstrapのcard使用 -->
		     	  <div class="card" style="width: 40rem;">
		  	       <div class="card-body">
		     		<%= link_to user_path(post) do %><%= attachment_image_tag post, :image, :fill, 300, 400, format: 'jpeg',class:"card-img-top", :width => "300", :height => "400" %>
					<% end %>
				    <%= link_to post_path(post.id), class:"card-subtitle" do %>
					    <%= post.body %>
					<% end %>
				    <%= link_to user_path(post.user.id), class:"card-link" do %>
					   <%= post.user.user_name %>
					<% end %>
					<div class="card-text">
					  <!-- コメント数、いいね数の算出 -->
					  <%= post.post_comments.count %>コメント
			          <%= post.post_goods.count %> いいね
			        </div>
			       </div>
		          </div>
			    </td>
		     </tr>
	</tbody>
</table>

app/views/user/posts/edit.html.erb
<div class="container">
  <div class="row">
  	<div class="col-3">
  	</div>
  	<div class="col-6">
		<h1 class="text-center">投稿フォーム</h1>
		<%= form_with(model: @post, url: post_path(@post), local: true) do |f| %>

		  <div class="text-center">
		  	 <div class="form-group">
		  	 	<div class="pt-5">
		  	 	   <%= f.attachment_field :image, class: 'img_field', style: 'display:none' %>
			       <%= attachment_image_tag @post, :image, :fill, 300, 300, fallback: 'm_e_others_500.png', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev', :width => "300", :height => "300" %>
			    </div>
			    <div class="pt-4">
				   <h4>趣味</h4>
				   <%= f.text_field :hobby_name, class:"form-control", placeholder:"※複数タグ付けする場合は趣味と趣味の間にスペースを入れてください"  %>
				</div>
				<div class="pt-4">
				   <h4>内容</h4>
				   <%= f.text_area :body, class:"form-control pb-5" %>
				</div>
			  </div>
			      <%= f.submit "編集する" %>
		  </div>
		<% end %>
	</div>
  </div>
</div>

app/views/user/posts/index.html.erb
<dev class="container">
    <div class="row">
      <div class="col-5">
        <!-- current_userのサイドメニュー -->
      	<%= render 'user/users/sidemenu' %>
      </div>
      <div class="col-7">
       <h1 class="pb-4">タイムライン</h1>
       <div style="overflow:auto; height: 500px;">
    		<% @posts.each do |post| %>
    		     <%= render 'timeline', post: post %>
    		<% end %>
       </div>
	  </div>
	</div>
</dev>

app/views/user/posts/new.html.erb
<!-- 投稿フォーム -->
<div class="container">
  <div class="row">
  	<div class="col-3">
  	</div>
  	<div class="col-6">
		<h1 class="text-center">投稿フォーム</h1>
		<%= form_with(model: @post, url: posts_path, local: true) do |f| %>

		  <div class="text-center">
		  	 <div class="form-group">
		  	 	<div class="pt-5">
		  	 	   <%= f.attachment_field :image, class: 'img_field', style: 'display:none' %>
		  	 	   <!-- 画像プレビュー機能　image_preview.jsから読み込み -->
			       <%= attachment_image_tag @post, :image, :fill, 300, 300, fallback: 'm_e_others_500.png', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev', :width => "300", :height => "300" %>
			    </div>
			    <div class="pt-4">
				   <h4>趣味</h4>
				   <%= f.text_field :hobby_name, class:"form-control", placeholder:"※複数タグ付けする場合は趣味と趣味の間にスペースを入れてください"  %>
				</div>
				<div class="pt-4">
				   <h4>内容</h4>
				   <%= f.text_area :body, class:"form-control pb-5" %>
				</div>
			  </div>
			      <%= f.submit "投稿", class:"btn btn-outline-success btn-lg mt-5" %>
		  </div>
		<% end %>
	</div>
  </div>
</div>

app/views/user/posts/show.html.erb
<!-- 投稿詳細 -->
<div class="container">
	<div class="row">
	  <div class="col-4">
	  </div>
	  <div class="col-8">
		<!-- 投稿内容　-->
		<div class="pb-4">
		<!-- 自身の投稿にのみ表示させる -->
		<% if @post.user == current_user %>
		    <%= link_to '編集', edit_post_path(@post), class:"btn btn-outline-success" %>
		    <%= link_to '削除', post_path(@post), method: :delete, class:"btn btn-outline-danger" %><br>
		    <% end %>
		</div>
		<!-- 投稿画像 -->
		<%= attachment_image_tag @post, :image,  format: 'jpeg', :width => "500", :height => "400" %><br >
		<!-- 投稿日時 -->
		<%= @post.created_at.strftime('%Y/%m/%d') %>
		<!-- タグ付けされた趣味、ワード取得し全部表示 -->
		<% @post_hobbies.each do |hobby| %>
		 <span><%= hobby.hobby_name %></span><br >
		<% end %>
	    <!-- 投稿したユーザーの画像 -->
		<%= attachment_image_tag @post.user, :image, :fill, 100, 100, fallback: 'no_image.jpg', :width => "80", :height => "80" %>
		<!-- 投稿したユーザーの名前 -->
		<%= @post.user.user_name %><br >
		<!-- 投稿内容 -->
		<%= @post.body %>
		<!-- いいね機能 -->
		<!-- current_userがいいねをしていたら -->
		<% if @post.post_gooded_by?(current_user) %>
		  <!-- いいね取り消し -->
		  <%= link_to post_post_good_path(@post), method: :delete do %>
		   <!-- ハートマークcss-->
		   <%= @post.post_goods.count %>
		    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
		  <% end %>
		<% else %>
		  <!-- いいねしていなかったらいいねをつける -->
		  <%= link_to post_post_goods_path(@post), method: :post do %>
		    <!-- いいねの数 -->
		    <%= @post.post_goods.count %>
		    <i class="fa fa-heart-o" aria-hidden="true"></i>
		  <% end %>
		<% end %>
		   <!-- コメント数 -->
		   	<%= @post.post_comments.count %>コメント
	   </div>
	</div>
    <div class="row pt-5">
      <div class="col-4">
      </div>
		<!--コメント表示-->
	  <div class="col-8">
		<div  style="overflow:auto; height: 300px;">
			<table class="table table-hover">
				<tbody>
					<% @post.post_comments.each do |post_comment| %>
					<tr>
						<td> <%= link_to user_path(post_comment), class:"text-secondary" do %>
							<%= attachment_image_tag post_comment.user, :image, :fill, 100, 100, fallback: 'no_image.jpg', :width => "50", :height => "50" %>
							<%= post_comment.user.user_name %>
						  <% end %>
						</td>
						<td><%= post_comment.comment %></td>
						<td><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
						<!-- そのコメントをしたユーザーにしか見えない -->
						<td><% if post_comment.user == current_user %>
							  <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, class:"text-danger" %><% end %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
	    </div>
        <div class="form-group pt-5">
				<!--コメント入力フォーム-->
				<%= form_for [@post, @post_comment] do |f| %>
				 <%= f.text_area :comment, class:"form-control" %>
				 <%= f.submit "コメントする", class:"" %>
				<% end %>
	    </div>
	   </div>
	</div>
</div>