config/routes.rb
Rails.application.routes.draw do

  scope module: 'user' do
    devise_for :users, controllers: {
      sessions: 'user/users/sessions',
      registrations: 'user/users/registrations',
      passwords: 'user/users/passwords'
    }
  end

  scope module: 'user' do
  	root :to => 'tops#top'
    get 'user_list' => 'users#user_list'
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :following, :followers
        get :matching
      end
    end
    resources :rooms, only: [:index, :show, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :posts do
   	  resources :post_goods, only: [:create, :destroy]
   	  resources :post_comments, only: [:create, :destroy]
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
	belongs_to :user
	belongs_to :room
	after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/entry.rb
class Entry < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/hobby.rb
class Hobby < ApplicationRecord
	has_many :hobby_maps, dependent: :destroy, foreign_key: 'hobby_id'
	has_many :posts, through: :hobby_maps
	has_many :user_hobby_maps, dependent: :destroy, foreign_key: 'hobby_id'
	has_many :users, through: :user_hobby_maps
end

app/models/hobby_map.rb
class HobbyMap < ApplicationRecord
	belongs_to :post
	belongs_to :hobby
	validates :post_id, presence: true
    validates :hobby_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

	default_scope -> { order(created_at: :desc) }
	attachment :image

    belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :post_goods, dependent: :destroy
	has_many :hobby_maps, dependent: :destroy
	has_many :hobbies, through: :hobby_maps

   def post_gooded_by?(user)
    post_goods.where(user_id: user.id).exists?
   end

   def save_hobby(sent_hobbies)
    current_hobbies = self.hobbies.pluck(:hobby_name) unless self.hobbies.nil?
    old_hobbies = current_hobbies - sent_hobbies
    new_hobbies = sent_hobbies - current_hobbies

    old_hobbies.each do |old|
      self.hobbies.delete Hobby.find_by(hobby_name: old)
    end

    new_hobbies.each do |new|
      new_hobby = Hobby.find_or_create_by(hobby_name: new)
      self.hobbies << new_hobby
    end
   end


end

app/models/post_comment.rb
class PostComment < ApplicationRecord
 belongs_to :user
 belongs_to :post
end

app/models/post_good.rb
class PostGood < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :entries, dependent: :destroy
	has_many :chat_messages, dependent: :destroy
	has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord

  attachment :image
  # ユーザー名1~15文字以内
  validates :user_name, length: { in: 1..15 }
  # 新規登録時性別記入必須にするため
  validates :sex, presence:true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum sex: {男性: 0, 女性: 1}

         enum area: {
            "---":0,
			北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
			茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
		    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
			岐阜県:21,静岡県:22,愛知県:23,三重県:24,
			滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
			鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
			徳島県:36,香川県:37,愛媛県:38,高知県:39,
			福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
			沖縄県:47
			}

	has_many :posts, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :post_goods, dependent: :destroy
	has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
	has_many :followings, through: :following_relationships
	has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
    has_many :followers, through: :follower_relationships
    has_many :entries
    has_many :chat_messages
    has_many :rooms, through: :entries
    has_many :user_hobby_maps, dependent: :destroy
    has_many :hobbies, through: :user_hobby_maps

	def following?(other_user)
		following_relationships.find_by(following_id: other_user.id)
	end

	def follow!(other_user)
		following_relationships.create!(following_id: other_user.id)
	end

	def unfollow!(other_user)
		following_relationships.find_by(following_id: other_user.id).destroy
	end

	def save_hobby(sent_hobbies)
	    current_hobbies = self.hobbies.pluck(:hobby_name) unless self.hobbies.nil?
	    old_hobbies = current_hobbies - sent_hobbies
	    new_hobbies = sent_hobbies - current_hobbies

	    old_hobbies.each do |old|
	      self.hobbies.delete Hobby.find_by(hobby_name: old)
	    end

	    new_hobbies.each do |new|
	      new_hobby = Hobby.find_or_create_by(hobby_name: new)
	      self.hobbies << new_hobby
	    end
    end
end

app/models/user_hobby_map.rb
class UserHobbyMap < ApplicationRecord
  belongs_to :user
  belongs_to :hobby
  validates :user_id, presence: true
  validates :hobby_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!

	def after_sign_in_path_for(resource)
      users_path(resource)
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :sex, :age])
  end
end

app/controllers/user/tops_controller.rb
class User::TopsController < ApplicationController
	skip_before_action :authenticate_user!
	def top
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/post_goods_helper.rb
module User::PostGoodsHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/rooms_helper.rb
module User::RoomsHelper
end

app/helpers/user/tops_helper.rb
module User::TopsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
	def current_user?(user)
		user == current_user
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>H2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar fixed-top navbar-dark bg-dark">
        <h3 class="text-light">Hobby Connection</h3>
      <!--ログインしていた場合表示されるヘッダー-->
        <ul class="list-unstyled list-inline">
              <% if user_signed_in? %>
                <li class="list-inline-item">
                  <%= link_to "マイページ", users_path, class: 'text-light' %>
                </li>
                <li class="list-inline-item">
                  <%= link_to '趣味仲間を探す', user_list_path, class: 'text-light' %>
                </li>
                <li class="list-inline-item">
                  <%= link_to "タイムライン", posts_path, class: 'text-light' %>
                </li>
                <li class="list-inline-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'text-light'  %>
                </li>
        <!--ログインしていない場合表示されるヘッダー-->
              <% else %>
              　<li class="list-inline-item">
                  <%= link_to "TOP", root_path, class: 'text-light' %>
                </li>
                <li class="list-inline-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'text-light' %>
                </li>
                <li class="list-inline-item">
                  <%= link_to "新規会員登録", new_user_registration_path, class: 'text-light' %>
                </li>
              <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <nav class="navbar fixed-bottom navbar-dark bg-dark">
    </footer>
  </body>
</html>